M48
; DRILL file {KiCad 8.0.4} date 2024-10-13T10:08:58+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-13T10:08:58+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0512
%
G90
G05
T1
X8.1656Y-4.6932
X8.1656Y-4.9208
T2
X3.113Y-4.603
X3.153Y-4.903
X3.193Y-4.603
T3
X3.8403Y-2.2806
X4.1553Y-2.2806
T4
X7.8047Y-2.436
T5
X7.5113Y-2.436
M30
