M48
; DRILL file {KiCad 9.0.1} date 2025-06-27T17:58:13+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-27T17:58:13+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0512
%
G90
G05
T1
X8.1656Y-4.6932
X8.1656Y-4.9208
T2
X3.113Y-4.603
X3.153Y-4.903
X3.193Y-4.603
T3
X3.8403Y-2.2373
X4.1553Y-2.2373
T4
X7.8036Y-2.381
T5
X7.5103Y-2.381
M30
